name: ghpages.yml

on:
  pull_request:
    branches: [main]
    types: [closed]
    paths:
      - 'vue/**'
      - '!vue/.gitignore'
      - '!vue/README.md'

defaults:
  run:
    working-directory: vue

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['18']
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    if: github.event.pull_request.merged == true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build --if-present
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          branch: 'main'
          deploy_key: ${{ secrets.DEPLOY_NAMELESS_HOUSEWORK_NOTIFICATION_KEY }}
          publish_branch: gh-pages
          publish_dir: ./vue/ghpages
