name: lint_vue.yml

on:
  push:
    paths:
      - 'vue/**'
      - '!vue/.gitignore'
      - '!vue/README.md'

defaults:
  run:
    working-directory: src

jobs:
  lint:
    name: lint_vue
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: echo "npm run codegen"
      - run: echo "cd ../vue && npm ci"
      - run: echo "npm run lint-vue"
