name: lint_api.yml

on:
  push:
    paths-ignore:
      - 'vue/**'
      - '@types/**'
      - 'docs/**'
      - 'graphql/**'
      - '.gitignore'
      - 'README.md'

defaults:
  run:
    working-directory: src

jobs:
  lint:
    name: lint_api
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm ci
      - run: npm run lint-api
